version: '3.8'

services:
  # Base de datos MySQL
  db-pohapp:
    image: mysql:latest
    restart: always
    container_name: pohapp-db-container
    hostname: pohapp-host
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: pohapp2024
      MYSQL_DATABASE: db-pohapp
    ports:
      - "3308:3306"
    volumes:
      - ./dbpohapp.sql:/docker-entrypoint-initdb.d/dbpohapp.sql

  # Backend
  pohapp-back:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - db-pohapp
    image: pohapp-back-image
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: pohapp2024
      DB_HOST: pohapp-host
      DB_USER: root
      DB_PORT: 3306
      DB_DATABASE: db-pohapp
    container_name: pohapp-back-container