services:

  # Backend
  pohapp-back:
    build:
      context: ../
      dockerfile: Dockerfile
    image: pohapp-back-image
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: pohapp2024
      DB_HOST: 172.18.0.4
      DB_USER: root
      DB_PORT: 3306
      DB_DATABASE: db-pohapp
    container_name: pohapp-back-container