#!/bin/bash

# Comandos Útiles para Pohapp Backend en Kubernetes
# Este archivo es una referencia rápida de comandos comunes

NAMESPACE="pohapp-backend"

echo "🚀 Comandos Útiles - Pohapp Backend Kubernetes"
echo "=============================================="
echo ""

# MONITOREO
echo "📊 MONITOREO"
echo "------------"
echo "# Ver todos los recursos"
echo "kubectl get all -n $NAMESPACE"
echo ""
echo "# Ver pods con detalles"
echo "kubectl get pods -n $NAMESPACE -o wide"
echo ""
echo "# Ver estado de deployments"
echo "kubectl get deployments -n $NAMESPACE"
echo ""
echo "# Ver servicios"
echo "kubectl get svc -n $NAMESPACE"
echo ""
echo "# Ver ingress"
echo "kubectl get ingress -n $NAMESPACE"
echo ""
echo "# Ver HPA (auto-escalado)"
echo "kubectl get hpa -n $NAMESPACE"
echo ""
echo "# Ver PVC (almacenamiento)"
echo "kubectl get pvc -n $NAMESPACE"
echo ""

# LOGS
echo "📜 LOGS"
echo "-------"
echo "# Ver logs del backend (todos los pods)"
echo "kubectl logs -f deployment/pohapp-backend -n $NAMESPACE"
echo ""
echo "# Ver logs de un pod específico"
echo "kubectl logs -f <nombre-pod> -n $NAMESPACE"
echo ""
echo "# Ver logs de MySQL"
echo "kubectl logs -f deployment/mysql -n $NAMESPACE"
echo ""
echo "# Ver logs anteriores (si un pod crasheó)"
echo "kubectl logs <nombre-pod> -n $NAMESPACE --previous"
echo ""
echo "# Ver últimas 100 líneas"
echo "kubectl logs deployment/pohapp-backend -n $NAMESPACE --tail=100"
echo ""

# DEBUGGING
echo "🔍 DEBUGGING"
echo "------------"
echo "# Describir pod (ver eventos y estado)"
echo "kubectl describe pod <nombre-pod> -n $NAMESPACE"
echo ""
echo "# Describir deployment"
echo "kubectl describe deployment pohapp-backend -n $NAMESPACE"
echo ""
echo "# Ver eventos del namespace"
echo "kubectl get events -n $NAMESPACE --sort-by='.lastTimestamp'"
echo ""
echo "# Ejecutar shell en pod del backend"
echo "kubectl exec -it deployment/pohapp-backend -n $NAMESPACE -- sh"
echo ""
echo "# Ejecutar comando en pod"
echo "kubectl exec deployment/pohapp-backend -n $NAMESPACE -- node --version"
echo ""

# MYSQL
echo "🗄️ MYSQL"
echo "--------"
echo "# Conectar a MySQL"
echo "kubectl exec -it deployment/mysql -n $NAMESPACE -- mysql -uroot -p"
echo ""
echo "# Hacer backup de MySQL"
echo "kubectl exec deployment/mysql -n $NAMESPACE -- mysqldump -uroot -p\$MYSQL_ROOT_PASSWORD db-pohapp > backup.sql"
echo ""
echo "# Restaurar backup"
echo "kubectl exec -i deployment/mysql -n $NAMESPACE -- mysql -uroot -p\$MYSQL_ROOT_PASSWORD db-pohapp < backup.sql"
echo ""
echo "# Ver espacio usado por MySQL"
echo "kubectl exec deployment/mysql -n $NAMESPACE -- df -h /var/lib/mysql"
echo ""

# SECRETS
echo "🔐 SECRETS"
echo "----------"
echo "# Ver secrets"
echo "kubectl get secrets -n $NAMESPACE"
echo ""
echo "# Ver contenido de un secret (base64)"
echo "kubectl get secret pohapp-backend-env-secrets -n $NAMESPACE -o yaml"
echo ""
echo "# Decodificar un secret"
echo "kubectl get secret pohapp-backend-env-secrets -n $NAMESPACE -o jsonpath='{.data.DB_PASSWORD}' | base64 -d"
echo ""
echo "# Eliminar y recrear secret"
echo "kubectl delete secret pohapp-backend-env-secrets -n $NAMESPACE"
echo "# Luego ejecutar GitHub Actions o crear manualmente"
echo ""

# DEPLOYMENT
echo "🚀 DEPLOYMENT"
echo "-------------"
echo "# Reiniciar deployment (sin downtime)"
echo "kubectl rollout restart deployment/pohapp-backend -n $NAMESPACE"
echo ""
echo "# Ver estado del rollout"
echo "kubectl rollout status deployment/pohapp-backend -n $NAMESPACE"
echo ""
echo "# Ver historial de rollouts"
echo "kubectl rollout history deployment/pohapp-backend -n $NAMESPACE"
echo ""
echo "# Rollback al deployment anterior"
echo "kubectl rollout undo deployment/pohapp-backend -n $NAMESPACE"
echo ""
echo "# Rollback a una revisión específica"
echo "kubectl rollout undo deployment/pohapp-backend -n $NAMESPACE --to-revision=2"
echo ""
echo "# Pausar rollout"
echo "kubectl rollout pause deployment/pohapp-backend -n $NAMESPACE"
echo ""
echo "# Reanudar rollout"
echo "kubectl rollout resume deployment/pohapp-backend -n $NAMESPACE"
echo ""

# ESCALAR
echo "📈 ESCALAR"
echo "----------"
echo "# Escalar manualmente"
echo "kubectl scale deployment pohapp-backend --replicas=5 -n $NAMESPACE"
echo ""
echo "# Ver métricas de pods"
echo "kubectl top pods -n $NAMESPACE"
echo ""
echo "# Ver métricas de nodos"
echo "kubectl top nodes"
echo ""

# RECURSOS
echo "⚙️ RECURSOS"
echo "-----------"
echo "# Actualizar límites de recursos"
echo "kubectl set resources deployment pohapp-backend -n $NAMESPACE --limits=cpu=2,memory=2Gi --requests=cpu=500m,memory=1Gi"
echo ""
echo "# Ver uso de recursos actual"
echo "kubectl describe node <node-name> | grep -A 5 pohapp-backend"
echo ""

# INGRESS & SSL
echo "🌐 INGRESS & SSL"
echo "----------------"
echo "# Ver ingress con detalles"
echo "kubectl describe ingress pohapp-backend-ingress -n $NAMESPACE"
echo ""
echo "# Ver certificados"
echo "kubectl get certificate -n $NAMESPACE"
echo ""
echo "# Ver detalles del certificado"
echo "kubectl describe certificate pohapp-backend-tls -n $NAMESPACE"
echo ""
echo "# Forzar renovación de certificado"
echo "kubectl delete certificate pohapp-backend-tls -n $NAMESPACE"
echo "# Cert-manager lo recreará automáticamente"
echo ""

# NETWORK
echo "🔌 NETWORK"
echo "----------"
echo "# Port-forward para acceso local"
echo "kubectl port-forward deployment/pohapp-backend 3000:3000 -n $NAMESPACE"
echo ""
echo "# Port-forward MySQL"
echo "kubectl port-forward deployment/mysql 3306:3306 -n $NAMESPACE"
echo ""
echo "# Probar conectividad entre pods"
echo "kubectl exec deployment/pohapp-backend -n $NAMESPACE -- nc -zv mysql-service 3306"
echo ""

# LIMPIEZA
echo "🧹 LIMPIEZA"
echo "-----------"
echo "# Eliminar pods en estado Error/Completed"
echo "kubectl delete pods --field-selector=status.phase!=Running -n $NAMESPACE"
echo ""
echo "# Eliminar todo el namespace (¡CUIDADO!)"
echo "kubectl delete namespace $NAMESPACE"
echo ""

# TROUBLESHOOTING
echo "🔧 TROUBLESHOOTING"
echo "------------------"
echo "# Pod no arranca - ver por qué"
echo "kubectl describe pod <nombre-pod> -n $NAMESPACE | grep -A 10 Events"
echo ""
echo "# ImagePullBackOff - verificar secret"
echo "kubectl get secret ghcr-secret -n $NAMESPACE"
echo ""
echo "# CrashLoopBackOff - ver logs"
echo "kubectl logs <nombre-pod> -n $NAMESPACE --previous"
echo ""
echo "# Probar conexión a MySQL desde backend"
echo "kubectl exec deployment/pohapp-backend -n $NAMESPACE -- nc -zv mysql-service 3306"
echo ""
echo "# Verificar variables de entorno"
echo "kubectl exec deployment/pohapp-backend -n $NAMESPACE -- env | grep DB_"
echo ""

# BACKUP
echo "💾 BACKUP"
echo "---------"
echo "# Backup completo de MySQL"
echo "kubectl exec deployment/mysql -n $NAMESPACE -- mysqldump -uroot -p\$MYSQL_ROOT_PASSWORD --all-databases > full-backup-\$(date +%Y%m%d).sql"
echo ""
echo "# Backup de configuración K8s"
echo "kubectl get all,configmap,secret,pvc,ingress -n $NAMESPACE -o yaml > pohapp-k8s-backup-\$(date +%Y%m%d).yaml"
echo ""

# PERFORMANCE
echo "⚡ PERFORMANCE"
echo "--------------"
echo "# Ver pods que más CPU consumen"
echo "kubectl top pods -n $NAMESPACE --sort-by=cpu"
echo ""
echo "# Ver pods que más memoria consumen"
echo "kubectl top pods -n $NAMESPACE --sort-by=memory"
echo ""
echo "# Ver requests y limits configurados"
echo "kubectl describe deployment pohapp-backend -n $NAMESPACE | grep -A 10 Limits"
echo ""

# GITHUB ACTIONS
echo "🤖 GITHUB ACTIONS"
echo "-----------------"
echo "# Ver último deployment via GitHub CLI"
echo "gh run list --limit 5"
echo ""
echo "# Ver logs de un workflow"
echo "gh run view <run-id> --log"
echo ""
echo "# Re-ejecutar último workflow"
echo "gh run rerun <run-id>"
echo ""

# QUICK FIXES
echo "🚑 QUICK FIXES"
echo "--------------"
echo "# Backend no responde - reiniciar"
echo "kubectl rollout restart deployment/pohapp-backend -n $NAMESPACE"
echo ""
echo "# MySQL no conecta - verificar secret y reiniciar"
echo "kubectl rollout restart deployment/mysql -n $NAMESPACE"
echo ""
echo "# SSL no funciona - verificar cert-manager"
echo "kubectl get certificate -n $NAMESPACE"
echo "kubectl describe certificate pohapp-backend-tls -n $NAMESPACE"
echo ""
echo "# HPA no escala - verificar metrics-server"
echo "kubectl get apiservices | grep metrics"
echo ""

echo ""
echo "=============================================="
echo "💡 TIP: Copia y pega estos comandos según necesites"
echo "📖 Para más info, ver: DEPLOYMENT.md"
echo "=============================================="
